spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/penjualan?useSSL=false&serverTimezone=Asia/Jakarta&createDatabaseIfNotExist=true
    username: root
    password: ""   # pakai XAMPP / default MySQL

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update   # auto create/update table
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
